# Generated by Django 5.2.11 on 2026-02-24 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("auth_method", models.CharField(max_length=50)),
                ("tenant", models.CharField(default="default", max_length=255)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("CREATE", "Create"), ("UPDATE", "Update"), ("DELETE", "Delete")],
                        max_length=10,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.IntegerField(null=True)),
                ("resource_repr", models.CharField(max_length=500)),
                ("endpoint", models.CharField(max_length=500)),
                ("http_method", models.CharField(max_length=10)),
                ("snapshot_before", models.JSONField(default=None, null=True)),
                ("snapshot_after", models.JSONField(default=None, null=True)),
                ("diff", models.JSONField(default=None, null=True)),
                ("response_code", models.IntegerField()),
                ("success", models.BooleanField()),
                ("event_type", models.CharField(default=None, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="auditlog_au_resourc_b28a0f_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"], name="auditlog_au_user_id_9831de_idx"
                    ),
                    models.Index(
                        fields=["action", "resource_type"], name="auditlog_au_action_4cb183_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "event_type"],
                        name="auditlog_au_resourc_c5bbfc_idx",
                    ),
                ],
            },
        ),
    ]
