# Generated by Django 5.2.6 on 2025-09-25 15:47

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("entityid", models.CharField(unique=True)),
                ("valid_for", models.IntegerField(default=8760)),
                ("autorenew", models.BooleanField(default=False)),
                ("metadata", models.CharField()),
                ("jwks", models.CharField(null=True)),
                ("required_trustmarks", models.CharField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("statement", models.CharField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["entityid"], name="entities_su_entityi_0bfba0_idx"),
                    models.Index(fields=["valid_for"], name="entities_su_valid_f_e25cdc_idx"),
                    models.Index(fields=["autorenew"], name="entities_su_autoren_f0d71e_idx"),
                ],
            },
        ),
    ]
