# Generated by Django 5.2.8 on 2025-12-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subordinate",
            name="additional_claims",
            field=models.JSONField(default=None, null=True),
        ),
    ]
