"""
Django settings for inmoradmin project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

# import sys
from pathlib import Path

from jwcrypto import jwk

from . import localsettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-28am!-fa@e-j@#9*=a^$=60oc7o5!ggp=r-(+5zs_u*4ebe2k4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    "trustmarks.apps.TrustmarksConfig",
    "entities.apps.EntitiesConfig",
    "apikeys.apps.ApikeysConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.mfa",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS Configuration (for frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
    "http://localhost:3000",  # Production frontend (Docker)
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins (for frontend making API requests)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# django-allauth settings
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"  # For development; set to "mandatory" in production
ACCOUNT_ALLOW_SIGNUPS = False  # Disable public registration; only admins can create users

ROOT_URLCONF = "inmoradmin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "inmoradmin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD": "",
        "HOST": os.environ.get("DB_HOST", "db"),
        "PORT": os.environ.get("DB_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

REDIS_LOCATION: str = os.environ.get("REDIS_LOCATION", "redis://redis:6379/0")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


# LOGGING = {
# "version": 1,
# "disable_existing_loggers": False,
# "formatters": {
# "verbose": {
# "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
# },
# },
# "handlers": {
# "console": {
# "level": "INFO",
# "class": "logging.StreamHandler",
# "stream": sys.stdout,
# "formatter": "verbose",
# },
# },
# "loggers": {
# "": {
# "handlers": ["console"],
# "level": "INFO",
# "propagate": True,
# },
# },
# }

# TA/IA configuration

SIGNING_PRIVATE_KEY = jwk.JWK.from_json(open("./private.json").read())
SIGNING_PUBLIC_KEYS = []

for pubkey in os.listdir("./publickeys"):
    if pubkey.endswith(".json") or pubkey.endswith(".pub"):
        pkey = jwk.JWK.from_json(open(os.path.join("./publickeys", pubkey)).read())
        SIGNING_PUBLIC_KEYS.append(pkey)

TA_DOMAIN = "https://localhost:8080"
TRUSTMARK_PROVIDER = "https://localhost:8080"
# We must have this, empty dictionary is okay
POLICY_DOCUMENT = {
    "metadata_policy": {},
}

SERVER_EXPIRY = 8760  # A year in hours

# Add authority_hints in case you are running Intermediate
AUTHORITY_HINTS = []

# TODO: make sure we have all the ones we need
FEDERATION_ENTITY = {
    "federation_fetch_endpoint": f"{TA_DOMAIN}/fetch",
    "federation_list_endpoint": f"{TA_DOMAIN}/list",
    "federation_resolve_endpoint": f"{TA_DOMAIN}/resolve",
    "federation_trust_mark_status_endpoint": f"{TA_DOMAIN}/trust_mark_status",
    "federation_trust_mark_list_endpoint": f"{TA_DOMAIN}/trust_mark_list",
    "federation_trust_mark_endpoint": f"{TA_DOMAIN}/trust_mark",
    "federation_historical_keys_endpoint": f"{TA_DOMAIN}/historical_keys",
}

HISTORICAL_KEYS_DIR = os.environ.get("HISTORICAL_KEYS_DIR", "./historical_keys")

SUBORDINATE_DEFAULT_VALID_FOR: int = 8760  # a year in hours

# The following are the default values the system will use while creating new entries via API.
TA_DEFAULTS = {
    "trustmarktype": {
        "autorenew": True,
        "valid_for": 8760,
        "renewal_time": 48,
        "active": True,
    },
    "trustmark": {
        "autorenew": True,
        "valid_for": 8760,
        "renewal_time": 48,
        "active": True,
    },
}

# The following are the trustmarks given to TA by an external entity
TA_TRUSTMARKS = []
# Any trusted trustmark issuers can be added in localsettings.py
TA_TRUSTED_TRUSTMARK_ISSUERS = {}

# django-allauth MFA settings
MFA_SUPPORTED_TYPES = ["totp", "webauthn"]
MFA_TOTP_ISSUER = "Inmor Admin"
MFA_WEBAUTHN_RP_NAME = "Inmor Admin"

# now see if we need to override any settings
for variable in dir(localsettings):
    if not variable.startswith("__"):
        # Then we set it
        globals()[variable] = getattr(localsettings, variable)
