"""
Django settings for inmoradmin project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from jwcrypto import jwk

from . import localsettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-28am!-fa@e-j@#9*=a^$=60oc7o5!ggp=r-(+5zs_u*4ebe2k4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    "trustmarks.apps.TrustmarksConfig",
    "entities.apps.EntitiesConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "inmoradmin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "inmoradmin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD": "",
        "HOST": os.environ.get("DB_HOST", "db"),
        "PORT": os.environ.get("DB_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

REDIS_LOCATION: str = os.environ.get("REDIS_LOCATION", "redis://redis:6379/0")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# TA/IA configuration

SIGNING_PRIVATE_KEY = jwk.JWK.from_json(open("./private.json").read())
SIGNING_PUBLIC_KEY = jwk.JWK.from_json(open("./public.json").read())
TA_DOMAIN = "http://localhost:8080"
TRUSTMARK_PROVIDER = "http://localhost:8080"
# We must have this, empty dictionary is okay
POLICY_DOCUMENT = {
    "metadata_policy": {},
    # FIXME: This should be for each subordinate separately in database
    "metadata": {},
}

SERVER_EXPIRY = 8760  # A year in hours

# Add authority_hints in case you are running Intermediate
AUTHORITY_HINTS = []

# TODO: make sure we have all the ones we need
FEDERATION_ENTITY = {
    "federation_fetch_endpoint": f"{TA_DOMAIN}/fetch",
    "federation_list_endpoint": f"{TA_DOMAIN}/list",
    "federation_resolve_endpoint": f"{TA_DOMAIN}/resolve",
    "federation_trust_mark_status_endpoint": f"{TA_DOMAIN}/trust_mark_status",
    "federation_trust_mark_list_endpoint": f"{TA_DOMAIN}/trust_mark_list",
    "federation_trust_mark_endpoint": f"{TA_DOMAIN}/trust_mark",
}

SUBORDINATE_DEFAULT_VALID_FOR: int = 8760  # a year in hours

# The following are the default values the system will use while creating new entries via API.
TA_DEFAULTS = {
    "trustmarktype": {
        "autorenew": True,
        "valid_for": 8760,
        "renewal_time": 48,
        "active": True,
    },
    "trustmark": {
        "autorenew": True,
        "valid_for": 8760,
        "renewal_time": 48,
        "active": True,
    },
}

# now see if we need to override any settings
for variable in dir(localsettings):
    if not variable.startswith("__"):
        # Then we set it
        globals()[variable] = getattr(localsettings, variable)
