# Generated by Django 5.2.11 on 2026-02-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apikeys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="tenant",
            field=models.CharField(
                default="default", help_text="Tenant this API key belongs to.", max_length=255
            ),
        ),
    ]
