# Generated by Django 5.2.8 on 2025-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trustmarks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustmark",
            name="additional_claims",
            field=models.JSONField(default=None, null=True),
        ),
    ]
