# Generated by Django 5.2.4 on 2025-09-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trustmarks", "0002_alter_trustmark_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustmarktype",
            name="valid_for",
            field=models.IntegerField(default=365),
        ),
        migrations.AlterField(
            model_name="trustmarktype",
            name="tmtype",
            field=models.CharField(unique=True),
        ),
    ]
